### ISSUE TITLE
[BUG] Use snapshots from distribution/maven for dependencies 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#274]
**Describe the bug**

There are -SNAPSHOT builds checked into https://github.com/opensearch-project/cross-cluster-replication/tree/main/src/test/resources/security/plugin. This is error prone at the very least, use a distribution build.

**Comment by saikaranam-amazon** [comment]
> There are -SNAPSHOT builds checked into https://github.com/opensearch-project/cross-cluster-replication/tree/main/src/test/resources/security/plugin. This is error prone at the very least, use a distribution build.

we have addressed this in this PR: https://github.com/opensearch-project/cross-cluster-replication/pull/296 but keeping this issue open until the distribution builds are published to maven to use in CI workflow

**Comment by rursprung** [comment]
why was this closed? it's not yet using opensearch-security from maven:
https://github.com/opensearch-project/cross-cluster-replication/blob/a3d0bf0308a556764e428fe6c1bd3539bd3eb190/.github/workflows/security-tests.yml#L26-L36

=> this ticket should IMHO be re-opened as it isn't resolved.

**Comment by prudhvigodithi** [comment]
Hey @ankitkala @rursprung just to connect the dots once the issue is resolved https://github.com/opensearch-project/security/issues/1801, the required zip files can be fetched from maven, if then can this issue be resolved?
@dblock @bbarani 
Example (once the zips are published to maven) as
`mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get  -DrepoUrl=https://aws.oss.sonatype.org/content/repositories/snapshots/  -Dartifact=org.opensearch.plugin:opensearch-security:1.3.0.0-SNAPSHOT:zip`

**Comment by rursprung** [comment]
you shouldn't have to manually run `mvn` in the GitHub Action - instead you should probably have the dependency in your `build.gradle` so that it also works in any other place where you build the project. otherwise you wouldn't really have to use maven but could just download the ZIP from any download location.

**Comment by prudhvigodithi** [comment]
> you shouldn't have to manually run `mvn` in the GitHub Action - instead you should probably have the dependency in your `build.gradle` so that it also works in any other place where you build the project. otherwise you wouldn't really have to use maven but could just download the ZIP from any download location.

Hey @rursprung, I have just added as an example, but yes its should be fetched as dependency in gradle.

**Comment by prudhvigodithi** [comment]
Hey Starting with release 2.1.0, we now have plugin zips in [maven repo](https://repo1.maven.org/maven2/org/opensearch/plugin/)
We should be good to remove the checked in zips from repo from 2.x branches.
https://github.com/opensearch-project/opensearch-build/issues/1916#issuecomment-1179276885
**SecurityZip maven**: https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-security/
@saikaranam-amazon @dblock @rursprung @ankitkala 
Thank you

**Comment by rursprung** [comment]
@prudhvigodithi: see my comment here: https://github.com/opensearch-project/index-management/pull/403#issuecomment-1179663724

i think what's still missing to resolve this is the publishing of the ZIP files to the snapshot maven repo during snapshot builds. unless i was looking in the wrong place...? but then the solution for index-management is IMHO still wrong.

**Comment by prudhvigodithi** [comment]
Hey @rursprung, official release zips are part of [maven repo](https://repo1.maven.org/maven2/org/opensearch/plugin/), snapshots can be fetched from [nexus maven repo](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/)
Example for [job-scheduler snapshots] (https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-job-scheduler/)

**Comment by prudhvigodithi** [comment]
Just to add the PluginZips are out in maven starting 2.1.0, 1.x versions have to be backfilled.
Thank you
@rursprung @dblock @bbarani

**Comment by prudhvigodithi** [comment]
Just to add the PluginZips are out in maven starting 2.1.0, 1.x versions have to be backfilled.
Thank you
@rursprung @dblock @bbarani

**Comment by bbarani** [comment]
@saikaranam-amazon @ankitkala whats the next step here?

**Comment by ankitkala** [comment]
We'll  take this up in upcoming 1-2 weeks. @bbarani Are there any timelines you're looking at?

**Comment by ankitkala** [comment]
Closing the issue now.
